### ISSUE TITLE
es-cache requires other dependencies

### ISSUE THREAD

**Issue by QuentinWidlocher** [InHeap/es-cache#1]
Hi, great tool, pretty simple and up for the task but when adding `es-cache` to a node project and running it, I got these errors :

```
> node_modules/es-cache/dist/store/Memcache.js:15:67: error: Could not resolve "memcached" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    15 │ ...emcached = await Promise.resolve().then(() => require('memcached'));
       ╵                                                          ~~~~~~~~~~~

> node_modules/es-cache/dist/store/Redis.js:18:63: error: Could not resolve "redis" (use "./redis" to reference the file "node_modules/es-cache/dist/store/redis.js")
    18 │ ...   let redis = await Promise.resolve().then(() => require('redis'));
       ╵                                                              ~~~~~~~
```

Adding `memcached` and `redis` to my project solved the issue but maybe you should mention it in the readme on include theses dependencies in your project ?

Also, it's a bit of a shame I have to add `memcached` and `redis` since I only use the local store but it's not that important to me

**Comment by nitinbansal1989** [comment]
Hi, thanks for the feedback. redis and memcached are optional dependency. Only required when you are using redis store or memcache store respectively. 
If local store is used then these dependencies are not required.  Please check if redis or memcache store has been initialised in app somewhere.

**Comment by QuentinWidlocher** [comment]
I tried to remove redis and memcached from my project and launched it, I still got the same error as in my previous message.

I use yarn and here is my `package.json`

<details>
<summary>package.json</summary>

```json
{
  "private": true,
  "name": "remix-app-template",
  "description": "",
  "license": "",
  "scripts": {
    "build": "remix build",
    "dev": "remix dev",
    "postinstall": "remix setup node",
    "deploy": "fly deploy --remote-only",
    "start": "remix-serve build"
  },
  "dependencies": {
    "@remix-run/react": "^1.1.3",
    "@remix-run/serve": "^1.1.3",
    "dotenv": "^16.0.0",
    "es-cache": "^1.2.0",
    "github-api": "^3.4.0",
    "iconoir-react": "^2.1.0",
    "postcss": "^8.4.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "remix": "^1.1.3",
    "remix-tailwind": "^0.2.1",
    "tailwindcss": "^3.0.22"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.1.3",
    "@types/react": "^17.0.24",
    "@types/react-dom": "^17.0.9",
    "prettier": "^2.5.1",
    "prettier-plugin-tailwindcss": "^0.1.7",
    "typescript": "^4.1.2"
  },
  "engines": {
    "node": ">=14"
  },
  "sideEffects": false
}
```

</details>

Is there something else I can do ?

**Comment by nitinbansal1989** [comment]
Hi,

Please upgrade to latest version 1.3.1. Let me know if you are still facing this issue.

**Comment by QuentinWidlocher** [comment]
Hi, the error seems to be different. The 1.3.1 version require ESM style imports but I cannot use this due to an other tool in my project (Remix).

<details>
<summary>The error</summary>

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /mnt/809EB2A59EB292E0/Perso/Remix/personal-website/node_modules/es-cache/dist/index.js from /mnt/809EB2A59EB292E0/Perso/Remix/personal-website/build/index.js not supported.
Instead change the require of /mnt/809EB2A59EB292E0/Perso/Remix/personal-website/node_modules/es-cache/dist/index.js in /mnt/809EB2A59EB292E0/Perso/Remix/personal-website/build/index.js to a dynamic import() which is available in all CommonJS modules.
```

</details>

I tried to create another project to try it out, but I still get another error.

<details>
<summary>The error</summary>

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/mnt/809EB2A59EB292E0/Perso/Remix/test-es-cache/node_modules/es-cache/dist/types' is not supported resolving ES modules imported from /mnt/809EB2A59EB292E0/Perso/Remix/test-es-cache/node_modules/es-cache/dist/index.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:412:17)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///mnt/809EB2A59EB292E0/Perso/Remix/test-es-cache/node_modules/es-cache/dist/types'
}
```

</details>

<details>
<summary>package.json</summary>

```json
{
  "name": "test-es-cache",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "es-cache": "1.3.1"
  },
  "type": "module"
}
```

</details>

<details>
<summary>index.js</summary>

```js
import Cache from 'es-cache';
var cache = new Cache();

// now just use the cache

cache.put('foo', 'bar');
console.log(cache.get('foo'))

// that wasn't too interesting, here's the good part

cache.put('houdini', 'disappear', 100) // Time in ms
console.log('Houdini will now ' + cache.get('houdini'));

setTimeout(function() {
  console.log('Houdini is ' + cache.get('houdini'));
}, 200);
```

</details>

Maybe I'm doing something wrong here ?

**Comment by QuentinWidlocher** [comment]
No sorry, here is my test project content :

<details>
<summary>package.json</summary>

```json
{
  "name": "test-es-cache",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "es-cache": "1.4.1"
  },
  "type": "module"
}
```

</details>

<details>
<summary>index.js</summary>

```js
import Cache from 'es-cache';
const cache = new Cache();

// now just use the cache

cache.put('foo', 'bar');
console.log(cache.get('foo'))

// that wasn't too interesting, here's the good part

cache.put('houdini', 'disappear', 100) // Time in ms
console.log('Houdini will now ' + cache.get('houdini'));

setTimeout(function () {
  console.log('Houdini is ' + cache.get('houdini'));
}, 200);

```

</details>

<details>
<summary>node_modules/</summary>

```
@inheap
@redis
cluster-key-slot
connection-parse
es-cache
generic-pool
hashring
jackpot
memcached
redis
retry
simple-lru-cache
yallist            
```

</details>

<details>
<summary>The error I get when running "node index.js" with Node 16</summary>

```
(node:73913) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
es-cache-test/node_modules/es-cache/dist/index.js:1
import * as types from './types';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)      
```

</details>

As you can see, the import does not work, and installing the packages resolves `redis` and `memcached` even though the example does not use them.

**Comment by nitinbansal1989** [comment]
Hi, please update to version 1.4.4. I have fixed the module system and now it should work with both esm and commonjs modules

**Comment by QuentinWidlocher** [comment]
Using the same test project with version 1.4.4, I still encounter the same issue
